pipeline {
     agent any
     triggers {
          pollSCM('* * * * *')
     }
     stages {
          stage("Compile") {
               steps {
                    dir('sample1') {
                         sh "./gradlew compileJava"
                    }
               }
          }
          stage("Unit test") {
               steps {
                    dir('sample1') {
                         sh "./gradlew test"
                    }
               }
          }
          stage("Code coverage") {
               steps {
                    dir('sample1') {
                         sh "./gradlew jacocoTestReport"
                         sh "./gradlew jacocoTestCoverageVerification"
                    }
               }
          }
          stage("Static code analysis") {
               steps {
                    dir('sample1') {
                         sh "./gradlew checkstyleMain"
                    }
               }
          }
          stage("Package") {
               steps {
                    dir('sample1') {
                         sh "./gradlew build"
                    }
               }
          }

          stage("Docker build") {
               steps {
                    dir('sample1') {
                         sh "docker build -t davnfs/calculator:${BUILD_TIMESTAMP} ."
                    }
               }
          }

          stage("Docker push") {
               steps {
                    dir('sample1') {
                         sh "docker push davnfs/calculator:${BUILD_TIMESTAMP}"
                    }
               }
          }

          stage("Update version") {
               steps {
                    dir('sample1') {
                         sh "sed -i 's/{{VERSION}}/${BUILD_TIMESTAMP}/g' deployment.yaml"
                    }
               }
          }

          stage("Deploy to staging") {
               steps {
                    dir('sample1') {
                         sh "kubectl config use-context staging"
                         sh "kubectl apply -f hazelcast.yaml"
                         sh "kubectl apply -f deployment.yaml"
                         sh "kubectl apply -f service.yaml"
                    }
               }
          }

          stage("Acceptance test") {
               steps {
                    sleep 60
                    dir('sample1') {
                         sh "chmod +x acceptance-test.sh && ./acceptance-test.sh"
                    }
               }
          }

          stage("Performance test") {
               steps {
                    dir('sample1') {
                         sh "chmod +x performance-test.sh && ./performance-test.sh"
                    }
               }
          }

          stage("Release") {
               steps {
                    dir('sample1') {
                         sh "kubectl config use-context production"
                         sh "kubectl apply -f hazelcast.yaml"
                         sh "kubectl apply -f deployment.yaml"
                         sh "kubectl apply -f service.yaml"
                    }
               }
          }
          stage("Smoke test") {
               steps {
                    sleep 60
                    dir('sample1') {
                         sh "chmod +x smoke-test.sh && ./smoke-test.sh"
                    }
               }
          }
     }
}
