pipeline {
     agent any
     triggers {
          pollSCM('* * * * *')
     }
     stages {
          stage("Docker build") {
               steps {
                    dir('exercise2') {
                         sh "docker build -t davnfs/hello-service:${BUILD_TIMESTAMP} ."
                    }
               }
          }

          stage("Docker push") {
               steps {
                    dir('exercise2') {
                         sh "docker push davnfs/hello-service:${BUILD_TIMESTAMP}"
                    }
               }
          }

          stage("Update version") {
               steps {
                    dir('exercise2') {
                         sh "sed  -i 's/{{VERSION}}/${BUILD_TIMESTAMP}/g' deployment.yaml"
                    }
               }
          }
          
          stage("Deploy to staging") {
               steps {
                    dir('exercise2') {
                         sh "kubectl config use-context staging"
                         sh "kubectl apply -f deployment.yaml"
                    }
               }
          }

          stage("Performance test") {
               steps {
                    sleep 20
                    dir('exercise2') {
                         sh "chmod +x performance-test.sh && ./performance-test.sh"
                    }
               }
          }
     }
}
